version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '4000:4000'
      - '8081:8081'
    env_file:
      - .env
