# https://kubernetes.github.io/ingress-nginx/deploy/#quick-start
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: beta
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: prisma.localdev.me
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: nestjs-api-svc
                port:
                  number: 4000
