name: Lint

on:
  pull_request:
    branches: '**'
  push:
    branches: [dev, develop, main]

# Cancel in-progress workflow runs on PRs when a new commit is pushed.
# Does not cancel any runs on `develop` or `master` branches.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run Prettier
        run: pnpm run format:check
      - name: Run prisma genarate
        run: pnpm run prisma:generate
      - name: Run test
        run: pnpm run test
